// BIST'te aktif olarak işlem gören tüm hisseler (TradingView API'den, ETF'ler hariç)
// Format: [sembol, kısa ad]
export const BIST_STOCKS = [
  ["A1CAP","A1 Capital Yatitim Menkul Degerler"],["A1YEN","A1 Yenilenebilir Enerji Uretim"],["AAGYO","Agaoglu Avrasya Gayrimenkul YO"],["ACSEL","Aciselsan Acipayam Seluloz"],["ADEL","Adel Kalemcilik"],
  ["ADESE","Adese GYO"],["ADGYO","Adra Gayrimenkul YO"],["AEFES","Anadolu Efes Biracilik ve Malt"],["AFYON","Afyon Cimento"],["AGESA","AgeSA Hayat ve Emeklilik"],
  ["AGHOL","AG Anadolu Grubu Holding"],["AGROT","Agrotech Yuksek Teknoloji ve Yatirim"],["AGYO","Atakule Gayrimenkul YO"],["AHGAZ","Ahlatci Dogal Gaz Dagitim Enerji ve .."],["AHSGY","Ahes Gayrimenkul YO"],
  ["AKBNK","Akbank"],["AKCNS","Akcansa Cimento"],["AKENR","Akenerji Elektrik Uretim"],["AKFGY","Akfen Gayrimenkul YO"],["AKFIS","Akfen insaat Turizm ve"],
  ["AKFYE","AKFEN YENILENEBILIR ENERJI"],["AKGRT","Aksigorta"],["AKHAN","Akhan Un Fabrikasi Ve Tarim Urunleri.."],["AKMGY","Akmerkez Gayrimenkul YO"],["AKSA","Aksa Akrilik Kimya"],
  ["AKSEN","Aksa Enerji Uretim"],["AKSGY","Akis Gayrimenkul YO"],["AKSUE","Aksu Enerji ve"],["AKYHO","Akdeniz Yatirim Holding"],["ALARK","Alarko Holding"],
  ["ALBRK","Albaraka Turk Katilim Bankasi"],["ALCAR","Alarko Carrier"],["ALCTL","Alcatel Lucent Teletas Telekomunikas.."],["ALFAS","ALFA SOLAR ENERJI"],["ALGYO","Alarko Gayrimenkul YO"],
  ["ALKA","Alkim Kagit"],["ALKIM","Alkim Alkali Kimya"],["ALKLC","Altinkilic Gida ve Sut"],["ALTIN","DARPHANE ALTIN SERTIFIKASI"],["ALTNY","Altinay Savunma Teknolojileri"],
  ["ALVES","Alves Kablo"],["ANELE","Anel Elektrik Proje Taahhut ve"],["ANGEN","Anatolia Tani ve Biyoteknoloji Urunl.."],["ANHYT","Anadolu Hayat Emeklilik"],["ANSGR","Anadolu Anonim Turk Sigorta Sirketi"],
  ["ARASE","Dogu Aras Enerji Yatirimlari"],["ARCLK","Arcelik"],["ARDYZ","ARD Grup Bilisim Teknolojileri"],["ARENA","Arena Bilgisayar"],["ARFYE","ARF Bio Yenilenebilir Enerji Uretim"],
  ["ARMGD","Armada Gida"],["ARSAN","Arsan Holding"],["ARTMS","Artemis Hali"],["ARZUM","Arzum Elektrikli Ev Aletleri"],["ASELS","Aselsan Elektronik"],
  ["ASGYO","ASCE GAYRIMENKUL YO"],["ASTOR","Astor Enerji"],["ASUZU","Anadolu Isuzu Otomotiv"],["ATAGY","Ata Gayrimenkul YO"],["ATAKP","Atakey Patates Gida"],
  ["ATATP","ATP Yazilim ve Teknoloji"],["ATATR","Ata Turizm Isletmecilik Tasimacilik .."],["ATEKS","Akin Tekstil"],["ATLAS","Atlas Menkul Kiymetler YO"],["ATSYH","Atlantis Yatirim Holding"],
  ["AVGYO","Avrasya Gayrimenkul YO"],["AVHOL","Avrupa Yatirim Holding"],["AVOD","A.V.O.D. KURUTULMUS GIDA VE TARIM UR.."],["AVPGY","Avrupakent Gayrimenkul YO SA"],["AVTUR","Avrasya Petrol ve Turistik Tesisler .."],
  ["AYCES","Altin Yunus Cesme Turistik Tesisler"],["AYDEM","Aydem Yenilenebilir Enerji"],["AYEN","Ayen Enerji"],["AYES","Ayes Celik Hasir ve Cit"],["AYGAZ","Aygaz"],
  ["AZTEK","Aztek Teknoloji Urunleri"],["BAGFS","Bagfas Bandirma Gubre Fabrikalari"],["BAHKM","Bahadir Kimya"],["BAKAB","Bak Ambalaj"],["BALAT","Balatacilar Balatacilik"],
  ["BALSU","Balsu Gida"],["BANVT","Banvit Bandirma Vitaminli Yem"],["BARMA","Barem Ambalaj"],["BASCM","Bastas Baskent Cimento"],["BASGZ","Baskent Dogalgaz Dagitim Gayrimenkul.."],
  ["BAYRK","BAYRAK EBT TABAN"],["BEGYO","Bati Ege Gayrimenkul YO"],["BERA","Bera Holding"],["BESLR","Besler Gida Ve Kimya"],["BESTE","Best Brands Grup Enerji Yatirim"],
  ["BEYAZ","Beyaz Filo Oto Kiralama"],["BFREN","Bosch Fren Sistemleri"],["BIENY","Bien Yapi Urunleri Turizm Ve"],["BIGCH","Buyuk Sefler Gida Turizm Tekstil Dan.."],["BIGEN","Birlesim Grup Enerji Yatirimlari"],
  ["BIGTK","Big Medya Teknoloji"],["BIMAS","BIM Birlesik Magazalar"],["BINBN","Bin Ulasim Ve Akilli Sehir Teknoloji.."],["BINHO","1000 Yatirimlar Holding"],["BIOEN","BIotrend Cevre ve EnerjI Yatirimlari"],
  ["BIZIM","Bizim Toptan SatiG Magazalari"],["BJKAS","Besiktas Futbol Yatirimlari"],["BLCYT","Bilici Yatirim"],["BLUME","Blume Metal Kimya"],["BMSCH","BMS Celik Hasir"],
  ["BMSTL","BMS Birlesik Metal"],["BNTAS","Bantas Bandirma Ambalaj"],["BOBET","Bogazici Beton"],["BORLS","Borlease Otomotiv"],["BORSK","Bor Seker"],
  ["BOSSA","Bossa Isletmeleri"],["BRISA","Brisa Bridgestone Sabanci Lastik"],["BRKO","Birko Birlesik Koyunlulular Mensucat.."],["BRKSN","Berkosan Yalitim ve Tecrit Maddeleri.."],["BRKVY","Birikim Varlik Yonetim"],
  ["BRLSM","Birlesim Muhendislik Isitma Sogutma .."],["BRMEN","Birlik Mensucat Isletmesi"],["BRSAN","BORUSAN BIRLESIK BORU FABRIKALARI"],["BRYAT","Borusan Yatirim ve Pazarlama"],["BSOKE","Batisoke Soke Cimento"],
  ["BTCIM","Baticim Bati Anadolu Cimento"],["BUCIM","Bursa Cimento Fabrikasi"],["BULGS","Bulls GSYO"],["BURCE","Burcelik Bursa Celik Doekum"],["BURVA","Burcelik Vana"],
  ["BVSAN","BULBULOGLU VINC"],["BYDNR","Baydoner Restoranlari"],["CANTE","CAN2 TERMIK"],["CASA","Casa Emtia Petrol Kimyevi ve Turevleri"],["CATES","Cates Elektrik Uretim"],
  ["CCOLA","Coca-Cola Icecek"],["CELHA","Celik Halat ve Tel"],["CEMAS","Cemas Dokum"],["CEMTS","Cemtas Celik Makina"],["CEMZY","CEM ZEYTIN"],
  ["CEOEM","CEO Event Medya"],["CGCAM","Cagdas Cam"],["CIMSA","Cimsa Cimento"],["CLEBI","Celebi Hava Servisi"],["CMBTN","Cimbeton Hazir Beton ve Prefabrik Ya.."],
  ["CMENT","Cimentas Izmir Cimento Fabrikasi Turk"],["CONSE","Consus Enerji Isletmeciligi ve Hizme.."],["COSMO","Cosmos Yatirim Holding"],["CRDFA","Creditwest Faktoring"],["CRFSA","CarrefourSA Carrefour Sabanci Merkezi"],
  ["CUSAN","Cuhadaroglu Metal ve Pazarlama"],["CVKMD","CVK MADEN ISLETMELERI A.S"],["CWENE","CW ENERJI MUHENDISLIK"],["DAGI","Dagi Giyim"],["DAPGM","DAP GAYRIMENKUL GELISTIRME"],
  ["DARDL","Dardanel Onentas Gida San"],["DCTTR","DCT Trading Dis"],["DENGE","Denge Yatirim Holding"],["DERHL","Derluks Yatirim Holding"],["DERIM","Derimod Konfeksiyon Ayakkabi Deri"],
  ["DESA","Desa Deri"],["DESPC","Despec Bilgisayar Pazarlama ve"],["DEVA","Deva Holding"],["DGATE","Datagate Bilgisayar Malzemeleri"],["DGGYO","Dogus Gayrimenkul YO"],
  ["DGNMO","Doganlar Mobilya Grubu Imalat"],["DIRIT","Diriteks Dirilis Tekstil"],["DITAS","Ditas Dogan Yedek Parca Imalat ve Te.."],["DMLKT","Emlak Konut Gayrimenkul YO A.S. 0 % .."],["DMRGD","DMR Unlu Mamuller Uretim Gida Toptan.."],
  ["DMSAS","Demisas Dokum Emaye Mamulleri"],["DNISI","Dinamik Isi Makina Yalitim Malzemeleri"],["DOAS","Dogus Otomotiv Servis ve"],["DOCO","DO & CO Aktiengesellschaft"],["DOFER","Dofer Yapi Maizemeleri"],
  ["DOFRB","DOF Robotik"],["DOGUB","Dogusan Boru ve"],["DOHOL","Dogan Sirketler Grubu Holding"],["DOKTA","Doktas Dokumculuk"],["DSTKF","Destek Finans Faktoring"],
  ["DUNYH","Dunya Holding"],["DURDO","Duran Dogan Basim ve Ambalaj"],["DURKN","Durukan Sekerleme"],["DYOBY","Dyo Boya Fabrikalari"],["DZGYO","Deniz Gayrimenkul YO"],
  ["EBEBK","EBEBEK MAGAZACILIK"],["ECILC","EIS Eczacibasi Ilac, Sinai ve Finans.."],["ECOGR","Ecogreen Enerji Holding"],["ECZYT","Eczacibasi Yatirim Holding Ortakligi"],["EDATA","E-Data Teknoloji Pazarlama"],
  ["EDIP","Edip GYO"],["EFOR","Efor Yatirim"],["EGEEN","Ege Endustri ve"],["EGEGY","Egeyapi Avrupa Gayrimenkul YO"],["EGEPO","Nasmed Ozel Saglik Hizmetleri"],
  ["EGGUB","Ege Gubre"],["EGPRO","Ege Profil"],["EGSER","Ege Seramik"],["EKGYO","Emlak Konut Gayrimenkul YO"],["EKIZ","Ekiz Kimya"],
  ["EKOS","Ekos Teknoloji ve Elektrik"],["EKSUN","Eksun Gida Tarim"],["ELITE","Elite Naturel Organik Gida"],["EMKEL","Emek Elektrik Endustrisi"],["EMNIS","Eminis Ambalaj"],
  ["EMPAE","Empa Elektronik"],["ENDAE","Enda Enerji Holding"],["ENERY","Enerya Enerji"],["ENJSA","Enerjisa Enerji"],["ENKAI","Enka Insaat ve"],
  ["ENPRA","Enpara Bank"],["ENSRI","Ensari Sinai Yatirimlar"],["ENTRA","IC Enterra Yenilenebilir Enerji"],["EPLAS","Egeplast Ege Plastik"],["ERBOS","Erbosan Erciyas Boru ve"],
  ["ERCB","Erciyas Celik Boru"],["EREGL","Eregli Demir Ve Celik Fabrikalari"],["ERSU","Ersu Meyve ve Gida"],["ESCAR","Escar Filo Kiralama Hizmetleri"],["ESCOM","Escort Teknoloji Yatirim"],
  ["ESEN","Esenboga Elektrik Uretim"],["ETILR","Etiler Gida ve Ticari Yatirimlar"],["ETYAT","Euro Trend YO"],["EUHOL","Euro Yatirim Holding"],["EUKYO","Euro Kapital YO"],
  ["EUPWR","Europower Enerji ve Otomasyon Teknol.."],["EUREN","Europen Endustri Insaat"],["EUYO","Euro Menkul Kiymet YO"],["EYGYO","EYG Gayrimenkul YO"],["FADE","Fade Gida Yatirim"],
  ["FENER","Fenerbahce Futbol"],["FLAP","Flap Kongre Toplanti Hizmetleri Otom.."],["FMIZP","Federal-Mogul Izmit Piston ve Pim Ur.."],["FONET","Fonet Bilgi Teknolojileri"],["FORMT","FORMET METAL VE CAM"],
  ["FORTE","FORTE BILGI ILETISIM TEKNOLOJILERI V.."],["FRIGO","Frigo-Pak Gida Maddeleri"],["FRMPL","Formul Plastik Ve Metal"],["FROTO","Ford Otomotiv"],["FZLGY","FUZUL GAYRIMENKUL YO"],
  ["GARAN","Turkiye Garanti Bankasi"],["GARFA","Garanti Faktoring"],["GATEG","Gate Group Teknoloji Medya Ve Siber .."],["GEDIK","Gedik Yat"],["GEDZA","Gediz Ambalaj"],
  ["GENIL","Gen Ilac ve Saglik Urunleri"],["GENKM","Gentas Kimya Pazarlama"],["GENTS","Gentas Dekoratif Yuzeyler"],["GEREL","Gersan Elektrik"],["GESAN","GIRISIM ELEKTRIK TAAHHUT VE"],
  ["GIPTA","Gipta Ofis Kirtasiye ve Promosyon Ur.."],["GLBMD","Global Menkul Degerler"],["GLCVY","GELECEK VARLIK YONETIMI A.S"],["GLRMK","Gulermak Agir Insaat Ve Taahhut"],["GLRYH","Guler Yatirim Holding"],
  ["GLYHO","Global Yatirim Holding"],["GMSTR","Istanbul Silver B Tipi Gumus Borsa Y.."],["GMTAS","Gimat Magazacilik Insaat"],["GOKNR","GOKNUR GIDA MADDELERI ENERJI IMALAT .."],["GOLTS","Goltas Goller Bolgesi Cimento"],
  ["GOODY","Goodyear Lastikleri"],["GOZDE","Gozde GSYO"],["GRNYO","Garanti YO"],["GRSEL","Gur-Sel Turizm Tasimacilik Ve Servis"],["GRTHO","Grainturk Holding"],
  ["GSDDE","GSD Denizcilik Gayrimenkul Insaat"],["GSDHO","GSD Holding"],["GSRAY","Galatasaray Sportif Sinai Veticari Y.."],["GUBRF","Gubre Fabrikalari"],["GUNDG","Gundogdu Gida Sut Urunleri Ve Dis"],
  ["GWIND","GALATA WIND ENERJI"],["GZNMI","Gezinomi Seyahat Turizm"],["HALKB","Turkiye Halk Bankasi"],["HATEK","Hateks Hatay Tekstil Isletmeleri"],["HATSN","Hat-San Gemi Insaa Bakim Onarim Deni.."],
  ["HDFGS","Hedef GSYO"],["HEDEF","Hedef Holding"],["HEKTS","Hekt"],["HKTM","HIDROPAR HAREKET KONTROL TEKNOLOJILE.."],["HLGYO","Halk Gayrimenkul YO"],
  ["HOROZ","Horoz Lojistik Kargo Hizmetleri Ve"],["HRKET","Hareket Proje Tasimaciligi ve Yuk Mu.."],["HTTBT","Hitit Bilgisayar Hizmetleri"],["HUBVC","Hub GSYO"],["HUNER","Hun Yenilenebilir Enerji Uretim"],
  ["HURGZ","Hurriyet Gazetecilik ve Matbaacilik"],["ICBCT","ICBC Turkey Bank"],["ICUGS","ICU GSYO"],["IDGYO","Idealist Gayrimenkul YO"],["IEYHO","Isiklar Enerji ve Yapi Holding"],
  ["IHAAS","Ihlas Haber Ajansi SA"],["IHEVA","Ihlas Ev Aletleri Imalat"],["IHGZT","Ihlas Gazetecilik"],["IHLAS","Ihlas Holding"],["IHLGM","Ihlas Gayrimenkul Proje Gelistirme ve"],
  ["IHYAY","Ihlas Yayin Holding"],["IMASM","IMAS Makina"],["INDES","Indeks Bilgisayar Sistemleri Muhendi.."],["INFO","INFO Yat. A.S"],["INGRM","Ingram Micro Bilisim Sistemleri"],
  ["INTEK","Innosa Teknoloji"],["INTEM","Intema Insaat ve Tesisat Malzemeleri.."],["INVEO","Inveo Yatirim Holding"],["INVES","Investco Holding"],["ISBIR","Isbir Holding"],
  ["ISBTR","Turkiye Is Bankasi Anonim Sirketi"],["ISCTR","Turkiye Is Bankasi Anonim Sirketi"],["ISDMR","Iskenderun Demir ve Celik"],["ISFIN","Is Finansal Kiralama"],["ISGSY","Is GSYO"],
  ["ISGYO","Is Gayrimenkul YO"],["ISKPL","Isik Plastik VE Dis Pazarlama"],["ISKUR","Turkiye Is Bankasi"],["ISMEN","Is Yat"],["ISSEN","Isbir Sentetik Dokuma"],
  ["ISYAT","Is YO"],["IZENR","Izdemir Enerji Elektrik Uretim"],["IZFAS","Izmir Firca"],["IZINV","Iz Yatirim Holding"],["IZMDC","Izmir Demir Celik"],
  ["JANTS","Jantsa Jant"],["KAPLM","Kaplamin Ambalaj"],["KAREL","Karel Elektronik SA"],["KARSN","Karsan Otomotiv ve"],["KARTN","Kartonsan Karton"],
  ["KATMR","Katmerciler Arac Ustu Ekipman"],["KAYSE","Kayseri Seker Fabrikasi"],["KBORU","Kuzey Boru"],["KCAER","Kocaer Celik"],["KCHOL","Koc Holding"],
  ["KENT","Kent Gida Maddeleri ve"],["KERVN","Kervansaray Yatirim Holding"],["KFEIN","Kafein Yazilim Hizmetleri"],["KGYO","KORAY GAYRIMENKUL YO"],["KIMMR","Ersan Alisveris Hizmetleri ve Gida"],
  ["KLGYO","Kiler Gayrimenkul YO"],["KLKIM","Kalekim Kimyevi Maddeler"],["KLMSN","Klimasan Klima"],["KLNMA","Turkiye Kalkinma ve Yatirim Bankasi"],["KLRHO","KILER Holding"],
  ["KLSER","Kaleseramik Canakkale Kalebodur Sera.."],["KLSYN","Koleksiyon Mobilya"],["KLYPV","Kalyon Gunes Teknolojileri Uretim"],["KMPUR","Kimteks Poliuretan"],["KNFRT","Konfrut Tarim"],
  ["KOCMT","Koc Metalurji"],["KONKA","Konya Kagit"],["KONTR","Kontrolmatik Teknoloji Enerji ve Muh.."],["KONYA","Konya Cimento"],["KOPOL","KOZA POLYESTER"],
  ["KORDS","Kordsa Teknik Tekstil"],["KOTON","Koton Magazacilik Tekstil"],["KRDMA","Kardemir Karabiik Demir celik"],["KRDMB","Kardemir Karabiik Demir celik"],["KRDMD","Kardemir Karabiik Demir celik"],
  ["KRGYO","Korfez Gayrimenkul YO"],["KRONT","Kron Teknoloji"],["KRPLS","Koroplast Temizlik Ambalaj Urunleri .."],["KRSTL","Kristal Kola ve Mesrubat"],["KRTEK","Karsu Tekstil ve"],
  ["KRVGD","Kervan Gida"],["KSTUR","Kustur Kusadasi Turizm Endustrisi"],["KTLEV","KATILIMEVIM TASARRUF FINANSMAN"],["KTSKR","Kutahya Seker Fabrikasi"],["KUTPO","Kutahya Porselen"],
  ["KUVVA","Kuvva Gida Yatirimlari"],["KUYAS","Kuyas Yatirim"],["KZBGY","KIZILBUK GAYRIMENKUL YO"],["KZGYO","Kuzugrup Gayrimenkul YO"],["LIDER","LDR Turizm"],
  ["LIDFA","Lider Faktoring"],["LILAK","Lila Kagit"],["LINK","Link Bilgisayar Sistemleri Yazilimi .."],["LKMNH","Lokman Hekim Engurusag Saglik, Turiz.."],["LMKDC","Limak Dogu Anadolu Cimento"],
  ["LOGO","Logo Yazilim"],["LRSHO","Loras Holding"],["LUKSK","Luks Kadife"],["LXGYO","Luxera Gayrimenkul YO"],["LYDHO","Lydia Holding"],
  ["LYDYE","Lydia Yesil Enerji kaynaklari"],["MAALT","Marmaris Altinyunus Turistik Tesisle.."],["MACKO","Mackolik Internet Hizmetleri"],["MAGEN","MARGUN ENERJI URETIM"],["MAKIM","MAKIM MAKINA TEKNOLOJILERI SANAYIVE"],
  ["MAKTK","Makina Takim Endustrisi"],["MANAS","Manas Enerji Yonetimi"],["MARBL","Tureks Turunc Madencilik Ic ve Dis"],["MARKA","Marka Yatirim Holding"],["MARMR","Marmara Holding"],
  ["MARTI","Marti Otel Isletmeleri"],["MAVI","Mavi Giyim"],["MCARD","Metropal Kurumsal Hizmetler"],["MEDTR","Meditera Tibbi Malzeme"],["MEGAP","Mega Polietilen Kopuk"],
  ["MEGMT","Mega Metal"],["MEKAG","Meka Global Makine Imalat"],["MEPET","Mepet Metro Petrol ve Tesisleri"],["MERCN","MERCAN KIMYA"],["MERIT","Merit Turizm Yatirim ve Isletmeleri"],
  ["MERKO","Merko Gida"],["METRO","Metro Ticari ve Mali Yatirimlar Hold.."],["MEYSU","Meysu Gida"],["MGROS","Migros"],["MHRGY","MHR Gayrimenkul YO"],
  ["MIATK","MIA Teknoloji"],["MMCAS","MMCari Yatirimlar A.S"],["MNDRS","Menderes Tekstil"],["MNDTR","Mondi Turkey Oluklu Mukavva Kagit ve.."],["MOBTL","Mobitel Iletisim Nizmetleri A.S"],
  ["MOGAN","Mogan Enerji Yatirim Holding"],["MOPAS","Mopas Marketcilik Gida"],["MPARK","MLP Saglik Hizmetleri"],["MRGYO","Marti Gayrimenkul YO"],["MRSHL","Marshall Boya ve Vernik"],
  ["MSGYO","Mistral Gayrimenkul YO"],["MTRKS","Matriks Finansal Teknolojiler"],["MTRYO","Metro YO"],["MZHLD","Mazhar Zorlu Holding"],["NATEN","Naturel Yenilenebilir Enerji"],
  ["NETAS","Netas Telekomunikasyon"],["NETCD","Netcad Yazilim"],["NIBAS","Nigbas Nigde Betonarte"],["NTGAZ","Naturelgaz"],["NTHOL","Net Holding"],
  ["NUGYO","Nurol Gayrimenkul YO"],["NUHCM","Nuh Cimento"],["OBAMS","Oba Makarnacilik"],["OBASE","Obase Bilgisayar ve Danismanlik Hizm.."],["ODAS","ODAS Elektrik Uretim"],
  ["ODINE","Odine Solutions Teknoloji"],["OFSYM","Ofis Yem Gida"],["ONCSM","ONCOSEM ONKOLOJIK SISTEMLER"],["ONRYT","Onur Yuksek Teknoloji"],["OPT25","OSMANLI P BIST TEM 25 END HY BYF"],
  ["OPTGY","Osmanli Pf. Kar Payi Od. BIST GYO En.."],["ORCAY","ORCAY ORTAKOY CAY"],["ORGE","Orge Enerji Elektrik Taahhut"],["ORMA","Orma Orman Mahsulleri Integre"],["OSMEN","Osmanli Yat"],
  ["OSTIM","Ostim Endustriyel Yatirimlar ve Isle.."],["OTKAR","Otokar Otomotiv ve Savunma"],["OTTO","OTTO HOLDING A.S"],["OYAKC","OYAK Cimento Fabrikalari"],["OYAYO","Oyak YO"],
  ["OYLUM","Oylum Sinai Yatirimlar"],["OYYAT","Oyak Yat"],["OZATD","OZATA DENIZCILIK"],["OZGYO","Ozderici Gayrimenkul YO"],["OZKGY","Ozak Gayrimenkul YO"],
  ["OZRDN","Ozerden Ambalaj"],["OZSUB","Ozsu Balik Uretim"],["OZYSR","Ozyasar Tel ve Galvanizleme"],["PAGYO","Panora Gayrimenkul YO"],["PAHOL","PASIFIK HOLDING A.S"],
  ["PAMEL","Pamel Yenilenebilir Elektrik Uretim"],["PAPIL","PAPILON SAVUNMA TEKNOLOJI VE A.S"],["PARSN","Parsan Makina Parcalari"],["PASEU","Pasifik Eurasia Lojistik dis"],["PATEK","Pasifik Teknoloji"],
  ["PCILT","PC Iletisim ve Medya Hizmetleri"],["PEKGY","Peker Gayrimenkul YO"],["PENGD","Penguen Gida"],["PENTA","Penta Teknoloji Urunleri Dagitim"],["PETKM","Petkim Petrokimya Holding"],
  ["PETUN","Pinar Entegre Et ve Un"],["PGSUS","Pegasus Hava Tasimaciligi"],["PINSU","Pinar Su ve Icecek"],["PKART","Plastikkart Akilli Kart Iletisim Sis.."],["PKENT","Petrokent Turizm"],
  ["PLTUR","PLATFORM TURIZM TASIMACILIK GIDA INS.."],["PNLSN","Panelsan Cati Cephe Sistemleri"],["PNSUT","Pinar Sut Mamulleri"],["POLHO","Polisan Holding"],["POLTK","Politeknik Metal"],
  ["PRDGS","PARDUS GSYO"],["PRKAB","Turk Prysmian Kablo ve Sistemleri"],["PRKME","Park Elektrik Uretim Madencilik"],["PRZMA","Prizma Pres Matbaacilik Yayincilik"],["PSDTC","Pergamon Status Dis"],
  ["PSGYO","Pasifik Gayrimenkul YO"],["QNBFK","QNB Finansal Kiralama"],["QNBTR","QNB Bank"],["QTEMZ","DJIST - Dow Jones Istanbul 20"],["QUAGR","Qua Granite Hayal Yapi ve Urunleri"],
  ["RALYH","Ral Yatirim Holding"],["RAYSG","Ray Sigorta"],["REEDR","Reeder Teknoloji"],["RGYAS","Ronesans GYO"],["RNPOL","Rainbow Polikarbonat"],
  ["RODRG","Rodrigo Tekstil"],["RTALB","RTA Laboratuvarlari Biyolojik Urunle.."],["RUBNS","Rubenis Tekstil"],["RUZYE","Ruzy Madencilik Ve Enerji Yatirimlari"],["RYGYO","Reysas Gayrimenkul YO"],
  ["RYSAS","Reysas Tasimacilik ve Lojistik"],["SAFKR","Safkar Ege Cooling Air Conditioning .."],["SAHOL","Haci Omer Sabanci Holding"],["SAMAT","Saray Matbaacilik Kagitcilik Kirtasi.."],["SANEL","San-El Muhendislik Elektrik Taahhut"],
  ["SANFM","SANIFOAM ENDUSTRI VE TUKETIM URUNLERI"],["SANKO","Sanko Pazarlama Ithalat Ihracat"],["SARKY","Sarkuysan Elektrolitik Bakir"],["SASA","Sasa Polyester"],["SAYAS","Say Yenilenebilir Enerji Ekipmanlari"],
  ["SDTTR","SDT Uzay ve Savunma Teknolojileri"],["SEGMN","Segmen Kardesler Gida Uretim ve Amba.."],["SEGYO","SEKER GAYRIMENKUL YO"],["SEKFK","Seker Finansal Kiralama"],["SEKUR","Sekuro Plastik Ambalaj"],
  ["SELEC","Selcuk Ecza Deposu"],["SELVA","SELVA GIDA"],["SERNT","Seranit Granit Seramik"],["SEYKM","Seyitler Kimya"],["SILVR","Silverline Endustri ve"],
  ["SISE","Turkiye Sise ve Cam Fabrikalari"],["SKBNK","Sekerbank"],["SKTAS","Soktas Tekstil"],["SKYLP","Skyalp Finansal Teknolojiler ve Dani.."],["SKYMD","Seker Yat"],
  ["SMART","Smartiks Yazilim"],["SMRTG","Smart Gunes Enerjisi Teknolojileri A.."],["SMRVA","Sumer Varlik Yonetim"],["SNGYO","Sinpas Gayrimenkul YO"],["SNICA","Sanica Isi"],
  ["SNPAM","Sonmez Pamuklu"],["SODSN","Sodas Sodyum"],["SOKE","Soke Degirmencilik"],["SOKM","Sok Marketler"],["SONME","Soenmez Filament Sentetik Iplik ve E.."],
  ["SRVGY","Servet Gayrimenkul YO"],["SUMAS","Sumas Suni Tahta ve Mobilya"],["SUNTK","Sun Tekstil"],["SURGY","Sur Tatil Evleri Gayrimenkul YO"],["SUWEN","Suwen Tekstil San. Paz"],
  ["SVGYO","Savur Gayrimenkul YO A.S"],["TABGD","TAB Gida"],["TARKM","Tarkim Bitki Koruma"],["TATEN","Tatlipinar Enerji Uretim"],["TATGD","Tat Gida"],
  ["TAVHL","TAV Havalimanlari Holding"],["TBORG","Turk Tuborg Bira ve Malt"],["TCELL","Turkcell Iletisim Hizmetleri"],["TCKRC","Kirac Galvaniz Telekominikasyon Meta.."],["TDGYO","Trend Gayrimenkul YO"],
  ["TEHOL","Tera Yatirim Teknoloji Holding"],["TEKTU","Tek-Art Insaat Turizm ve Yatirimlar"],["TERA","Tera Yat"],["TEZOL","Europap Tezol Paper Industry and Tra.."],["TGSAS","TGS Dis"],
  ["THYAO","Turk Hava Yollari"],["TKFEN","Tekfen Holding"],["TKNSA","Teknosa Ic ve Dis"],["TLMAN","Trabzon Liman Isletmeciligi"],["TMPOL","Temapol Polimer Plastik Ve Insaat A..S"],
  ["TMSN","Tumosan Motor Ve Traktor"],["TNZTP","TAPDI OKSIJEN OZEL SAGLIK VE EGITIM .."],["TOASO","Tofas Turk Otomobil Fabrikasi"],["TRALT","Turk Altin Isletmeleri"],["TRCAS","Turcas Holding"],
  ["TRENJ","TR Dogal Enerji Kaynaklari Arastirma.."],["TRGYO","Torunlar Gayrimenkul YO"],["TRHOL","Tera Financial Investments Holding"],["TRILC","Turk Ilac ve Serum"],["TRMET","TR Anadolu Metal Madencilik Isletmel.."],
  ["TSGYO","TSKB Gayrimenkul YO"],["TSKB","Turkiye Sinai Kalkinma Bankasi"],["TSPOR","Trabzonspor Sportif Yatirim ve Futbo.."],["TTKOM","Turk Telekomunikasyon"],["TTRAK","Turk Traktor ve Ziraat Makineleri"],
  ["TUCLK","Tugcelik Aluminyum ve Metal Mamulleri"],["TUKAS","Tukas Gida"],["TUPRS","Turkiye Petrol Rafinerileri"],["TUREX","TUREKS TURIZM TASIMACILIK"],["TURGG","TURKER PROJE GAYRIMENKUL VE YATIRIM .."],
  ["TURSG","Turkiye Sigorta"],["UCAYM","Ucay Muhendislik Enerji ve Iklimlend.."],["UFUK","Ufuk Yatirim Yonetim Ve Gayrimenkul"],["ULAS","Ulaslar Turizm Energi Tarim Gida ve .."],["ULKER","Ulker Biskuvi"],
  ["ULUFA","Ulusal Faktoring"],["ULUSE","Ulusoy Elektrik Imalat Taahhut ve"],["ULUUN","Ulusoy Un"],["UNLU","Unlu Yatirim Holding"],["USAK","Usak Seramik"],
  ["USDTR","Finans Asset Management American Dol.."],["VAKBN","Turkiye Vakiflar Bankasi Turk Anonim.."],["VAKFA","Vakif Faktoring"],["VAKFN","Vakif Finansal Kiralama"],["VAKKO","Vakko Tekstil ve Hazir Giyim Isletme.."],
  ["VANGD","Vanet Gida Ic ve Dis"],["VBTYZ","VBT Yazilim"],["VERTU","Verusaturk GSYO"],["VERUS","Verusa Holding"],["VESBE","Vestel Beyaz Esya"],
  ["VESTL","Vestel Elektronik"],["VKFYO","Vakif Menkul Kiymet YO"],["VKGYO","Vakif Gayrimenkul YO"],["VKING","Viking Kagit ve Seluloz"],["VRGYO","Vera Konsept Gayrimenkul YO"],
  ["VSNMD","Visne Madencilik Uretim"],["YAPRK","Yaprak Sut ve Besi Ciftikleri"],["YATAS","Yatas Yatak ve Yorgan"],["YAYLA","Yayla Enerji Uretim Turizm ve Insaat"],["YBTAS","Yibitas Yozgat Isci Birligi Insaat M.."],
  ["YEOTK","YEO Teknoloji Enerji ve Endustri"],["YESIL","Yesil Yatirim Holding"],["YGGYO","Yeni Gimat Gayrimenkul YO"],["YIGIT","Yigit Aku Malzemeleri Nakliyat Turiz.."],["YKBNK","Yapi ve Kredi Bankasi"],
  ["YKSLN","Yukselen Celik"],["YONGA","Yonga Mobilya"],["YUNSA","Yunsa Yunlu"],["YYAPI","Yesil Yapi Endustrisi"],["YYLGD","Yayla Agro Gida ve Nakliyat"],
  ["ZEDUR","Zedur Enerji ElekTrik Uretim"],["ZERGY","Zeray Gayrimenkul YO"],["ZGOLD","Ziraat Portfolio Gold Participation .."],["ZGYO","Z Gayrimenkul YO"],["ZOREN","Zorlu Enerji Elektrik Uretim"],
  ["ZRGYO","Ziraat Gayrimenkul YO"],
];
